easy_words = ['Diamond', 'Queen', 'Football', 'Kite', 'Laugh', 'Nectar', 'Flower', 'Infinity', 'Chocolate', 'Kind',
              'Zero', 'Wind', 'Avocado', 'Melody', 'young', 'comfortable', 'Cactus', 'Boy', 'Waffle', 'Turtle',
              'Pencil', 'Feather', 'Jellyfish', 'Cat', 'Happy', 'Vase', 'Bear', 'Door', 'Origami', 'King', 'Table',
              'Mountain', 'Bubble', 'Yummy', 'Orange', 'Red', 'Pizza', 'Visit', 'Candy', 'Dolphin', 'Popcorn', 'Family',
              'Backpack', 'Kangaroo', 'Up', 'Owl', 'Shadow', 'Watch', 'Unicorn', 'Bicycle', 'Pajamas', 'Harmony',
              'quit', 'Internet', 'Yellow', 'Volleyball', 'Friends', 'Guitar', 'Dog', 'Jelly', 'Nose', 'beautiful',
              'Bad', 'Baby', 'Exercise', 'Whistle', 'Whisper', 'Rock', 'Globe', 'Mango', 'Rainbow', 'Sun', 'Noodle',
              'Horizon', 'Nest', 'Echo', 'Envelope', 'Muffin', 'Fantasy', 'Lamp', 'Island', 'Morning', 'Nice', 'Ball',
              'Girl', 'Haven', 'Garden', 'Purple', 'Illuminate', 'nice', 'Blanket', 'Jump', 'Cloud', 'Adventure',
              'Glimmer', 'Dinosaur', 'Summit', 'Lemon', 'Sing', 'Cuddle', 'Octopus', 'healthy', 'Galaxy', 'Cake',
              'Watermelon', 'puzzle', 'Notebook', 'Tree', 'Fish', 'Insect', 'Water', 'Hat', 'Rabbit', 'Hammer', 'Youth',
              'Open', 'Night', 'Umbrella', 'Zipper', 'relax', 'happiness', 'Love', 'Couple', 'Elephant', 'Yogurt',
              'Lollipop', 'Mouse', 'Unveil', 'Lighthouse', 'Grass', 'Star', 'Giggle', 'X-ray', 'Sandwich', 'Delight',
              'Cute', 'Rain', 'Jacket', 'Quiet', 'Telescope', 'rich', 'Lemonade', 'Monkey', 'Egg', 'Ice', 'Train',
              'Anchor', 'Duck', 'Apple', 'Alligator', 'Igloo', 'Breeze', 'Green', 'Cherry', "funny", "legs", "house",
              "tomorrow", "date", "meeting", "delicious", "food", "well", "organized", "hungry", "hate", "blue",
              "lol", "boo"]

difficult_words = ['Prejudices', 'Plummeting', 'Inundated', 'Influx', 'remedy', 'Proliferation', 'Evident',
                   'Skim', 'Serene', 'parsimonious', 'Enfant', 'Abruptly', 'strobe', 'awestruck',
                   'Aimlessly', 'frugal', 'larks', 'phlegm',
                   'Ailments', 'harboring', 'Necessities', 'Inquisitive', 'foray', 'inquisitive', 'Imagery',
                   'reap', 'limb', 'proliferation', 'abbreviate', 'Emergent', 'Colloquial', 'Surge',
                   'Kudos', 'Plunge', 'rogue', 'wilting', 'enrolled', 'subdue', 'imposed', 'Slump', 'Annul',
                   'Citing', 'Mundane', 'slick', 'Stem', 'buoyed', 'cataclysmic',
                   'formidable', 'camaraderie', 'unwind', 'Hustle', 'relentless', 'Ornament', 'thrived', 'detest',
                   'delineated', 'Novelty', 'shindig', 'abundance', 'harness', 'wring', 'Hone', 'debut',
                   'ratified', 'Incandescent', 'Forth', 'Practices', 'Conveying', 'Fluctuation',
                   'amend', 'cavorting', 'Assertion', 'gown', 'reckoned', 'predominant', 'rod', 'vengeance',
                       'assuage', 'plums', 'awe', 'retractable', 'grimy', 'indulge', 'abruptly', 'esteemed', 'fissure',
                   'regaling', 'Scrutiny', 'suitors', 'innate', 'vanity', 'sinister', 'Plains', 'pursuits',
                   'embellished', 'rendezvous', 'Owing', 'horrid', 'ratcheted', 'Venturing', 'backfill', 'tinker',
                   'Counterparts', 'shears', 'Stimulus', 'Abrupt', 'professed', 'gory', 'Deteriorating', 'cultivating',
                   'Prudent', 'obviate', 'naysayer', 'stingy', 'vendetta', 'owing', 'Jovial',
                   'appeared', 'frank', 'inferno', 'goop', 'prattling', 'Plummet',
                   'Endures', 'poured', 'Tranquil', 'Emit', 'annul', 'Facilitates', 'ludicrous',
                   'Duller', 'redacted', 'braise', 'dispassionate', 'Quench', 'utterance', 'sulking', 'Intricate',
                   'cutlery', 'skim', 'spun', 'vetted', 'contraption', 'Perspiration', 'Unrivaled',
                   'rudimentary', 'embroidered', 'condiment', 'fib', 'knack', 'Adorned', 'demise', 'frustrating', 'lad',
                   'Quarries', 'brew', 'Implicitly', 'Knot', 'cram', 'Supersede', 'tinkling', 'rift',
                   'fluke', 'rye', 'tad', 'Purveyors', 'Luminary', 'leisure', 'strands', 'Occupancy', 'pulleys',
                   'attain', 'crapulous', 'realm', 'Exert', 'Curt', 'dam', 'rectified', 'lurking', 'allure',
                   'bustle', 'render', 'contenders', 'stranded', 'Prospect', 'Blunt',
                   'reverential', 'Bustling', 'charcoal', 'Bolted', 'Drab', 'dwelling', 'interloper', 'parry',
                   'Ornateness', 'tantamount', 'yarn', 'Opulent', 'ponder', 'frigid', 'garment', 'Depleted',
                   'contemplate', 'Reputable', 'Deserting', 'Abolish', 'Prowess', 'gloom', 'Apparatus',
                   'diligently', 'Drifting', 'Adolescent', 'Parsimonious',
                   'caveat', 'dwell', 'stalemate', 'strain', 'radiant', 'Cognition', 'wilting',
                   'Quiver', 'awning', 'Competent', 'levity', 'Fad', 'Stagnated', 'sparing', 'Vivid',
                   'aficionado', 'blissful', 'dabble', 'Dizzying', 'doormat', 'Radiant', 'Profusely',
                   'aphorisms', 'renowned', 'copious', 'whim', 'profusely', 'bonjour',
                   'blunder', 'Spare', 'Delineated', 'Altitude', "Volley", "Quilt", "Kettle", "Jigsaw", "Jovial",
                   "Nexus", "Enchant", "Pristine", "Quiescent", "Resonate", "Voyage", "ravenous", "throng",
                   "scampered", "delectable", "viands", "impeccably", "Jolly"]

easy_words_for_testing = ["extremely", "crowd", "ran", "raw", "avoid", "carefully", "reading", "speed"]

difficult_words_for_testing = ["arrayed", "loathe", "eschew", "emancipation", "loathe", "Violet", "Roller"]
