contractions_dict = {
    "I'm": "I am",
    "you're": "you are",
    "he's": "he is",
    "she's": "she is",
    "it's": "it is",
    "we're": "we are",
    "they're": "they are",
    "I've": "I have",
    "he'd": "he had",
    "she'd": "she had",
    "it'd": "it had",
    "we'd": "we had",
    "they'd": "they had",
    "I'll": "I will",
    "you'll": "you will",
    "he'll": "he will",
    "she'll": "she will",
    "it'll": "it will",
    "we'll": "we will",
    "they'll": "they will",
    "I'd": "I would",
    "you'd": "you would",
    "can't": "cannot",
    "isn't": "is not",
    "hasn't": "has not",
    "didn't": "did not",
    "doesn't": "does not",
    "haven't": "have not",
    "weren't": "were not",
    "shouldn't": "should not",
    "couldn't": "could not",
    "aren't": "are not",
    "don't": "do not",
    "mustn't": "must not",
    "wasn't": "was not",
    "i'll": "I will",
    "i've": "I have",
    "let's": "let us",
    "ma'am": "madam",
    "oughtn't": "ought not",
    "shan't": "shall not",
    "that's": "that is",
    "what's": "what is",
    "who's": "who is",
    "why's": "why is",
    "won't": "will not",
    "won't've": "will not have",
    "would've": "would have",
    "wouldn't've": "would not have",
    "y'all": "you all",
    "y'all'd": "you all would",
    "y'all'd've": "you all would have",
    "y'all're": "you all are",
    "y'all've": "you all have",
    "n't": "not",
    "e'er": "ever",
    "ne'er": "never",
    "kinda": "kind of",
    "sorta": "sort of",
    "gimme": "give me",
    "gotcha": "got you",
    "gonna": "going to",
    "wanna": "want to",
    "hafta": "have to",
    "hasta": "has to",
    "coulda": "could have",
    "shoulda": "should have",
    "woulda": "would have",
    "outta": "out of",
    "innit": "isn't it",
    "whatcha": "what are you",
    "waddaya": "what do you",
    "d'ya": "do you",
    "how'd": "how did",
    "howdy": "how do you do",
    "how're": "how are",
    "i'd've": "I would have",
    "i'm": "I am",
    "it'd've": "it would have",
    "mayn't": "may not",
    "might've": "might have",
    "mightn't": "might not",
    "must've": "must have",
    "needn't": "need not",
    "ol'": "old",
    "so's": "so is",
    "that'd": "that had",
    "that'd've": "that would have",
    "there's": "there is",
    "they'd've": "they would have",
    "they'll've": "they will have",
    "what'll": "what will",
    "what'll've": "what will have",
    "what've": "what have",
    "when's": "when is",
    "when've": "when have",
    "where'd": "where did",
    "where's": "where is",
    "where've": "where have",
    "who'll": "who will",
    "who'll've": "who will have",
    "who've": "who have",
    "why've": "why have",
    "will've": "will have",
    "wouldn't": "would not",
}
